const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
for(const mobile of [false,true])for(const reduced of [false,true]){
let progress=0;const w=mobile?390:1440,h=mobile?844:1000,attrs={},label={style:{}},form={style:{},inert:true},finale={style:{},querySelector(s){return s==='.access-form'?form:label}},brand={style:{}},light={style:{},querySelector(){return svg}},svg={setAttribute(k,v){attrs[k]=v},querySelector(){return polygon}},polygon={setAttribute(k,v){attrs[k]=v}};
const stage={offsetHeight:h,getBoundingClientRect(){return{left:0,top:0,width:w,height:h}}},story={offsetHeight:h*3.8,getBoundingClientRect(){return{top:-progress*h*2.8}}},image={style:{width:'1440',left:'0',top:'0'},addEventListener(){}},scene={dataset:{beyond:'false'},getBoundingClientRect(){return{left:0,top:0}},querySelector(s){return s==='img'?image:{getAttribute(){return '-11'}}},addEventListener(){}};
const nodes={'.scroll-story':story,'.observatory':stage,'.scene':scene,'.scroll-light':light,'.white-finale':finale,'header':brand};const listeners={};const body={dataset:{}};let raf,expanded,completed=0;
vm.runInNewContext(fs.readFileSync('dist/scroll.js','utf8'),{document:{body,addEventListener(n,f){listeners[n]=f},querySelector(s){return nodes[s]},dispatchEvent(e){if(e.type==="davinci:scroll")expanded=e.detail;if(e.type==="davinci:complete")completed++}},CustomEvent:class{constructor(name,data={}){this.detail=data.detail;this.type=name}},matchMedia(){return{matches:reduced,addEventListener(){}}},addEventListener(n,fn){listeners[n]=fn},requestAnimationFrame(fn){raf=fn;return 1},Math,Number,parseFloat});
function move(p){progress=p;listeners.scroll();raf();}
move(1);assert.equal(expanded,1);assert.equal(finale.style.visibility,'hidden');assert.equal(form.inert,true);move(0);scene.dataset.beyond='true';listeners['davinci:realm']();raf();assert.equal(form.inert,true);assert.equal(form.style.pointerEvents,'none');assert.equal(light.style.opacity,'0');assert.equal(finale.style.visibility,'hidden');move(.44);assert.equal(attrs.cx,w/2);assert.equal(attrs.cy,h/2);assert.ok(attrs.r>0&&attrs.r<Math.hypot(w,h)/2);assert.ok(Number(light.style.opacity)>0&&Number(light.style.opacity)<.1);move(.68);assert.equal(finale.style.clipPath,'none');assert.ok(Number(finale.style.opacity)>0&&Number(finale.style.opacity)<1);move(.6);assert.equal(expanded,1);assert.ok(attrs.r>0);move(0);assert.equal(finale.style.visibility,'hidden');assert.equal(form.inert,true);move(1);assert.equal(finale.style.clipPath,'none');assert.equal(finale.style.opacity,'1');assert.equal(label.style.opacity,'1');assert.equal(form.style.opacity,'1');assert.equal(form.inert,false);assert.equal(form.style.pointerEvents,'auto');assert.equal(brand.style.opacity,'0');assert.equal(body.dataset.finaleLocked,'true');assert.equal(scene.inert,true);assert.equal(completed,1);
scene.dataset.beyond='false';listeners['davinci:realm']();raf();move(0);assert.equal(form.inert,false);assert.equal(form.style.pointerEvents,'auto');assert.equal(finale.style.visibility,'visible');assert.equal(finale.style.opacity,'1');assert.equal(label.style.opacity,'1');assert.equal(brand.style.opacity,'0');assert.equal(expanded,1);assert.equal(completed,1);
if(reduced)assert.equal(label.style.transform,'none');
}
console.log('PASS: full viewport coverage, white finale, brand reveal, locked finale, mobile and reduced motion.');

assert.ok(fs.readFileSync('dist/index.html','utf8').includes('id="white-bloom"'));
